In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [ ]:
extracted=pd.read_csv('RFphish.csv',index_col=0)

In [ ]:
extracted.shape

(11430, 17)

In [ ]:
extracted.head()

Have_IP  Have_At  URL_Length  ...  iFrame  Deep_Learning  label
0        0        0           0  ...       0              0      0
1        0        0           0  ...       0              1      1
2        0        0           0  ...       1              1      1
3        0        0           0  ...       1              0      0
4        0        0           0  ...       0              0      0

[5 rows x 17 columns]

In [ ]:
extracted.drop(['hasHTTP','Deep_Learning'],axis=1,inplace=True)

In [ ]:
import json

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
extracted.shape

(11430, 15)

In [ ]:
X=extracted.drop(['label'],axis=1)

In [ ]:
X.head()

Have_IP  Have_At  URL_Length  ...  SFH  to_email  iFrame
0        0        0           0  ...    1         0       0
1        0        0           0  ...    1         0       0
2        0        0           0  ...    1         1       1
3        0        0           0  ...    1         1       1
4        0        0           0  ...    1         0       0

[5 rows x 14 columns]

In [ ]:
y=extracted['label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=42)

In [ ]:
test_data = dict()
test_data['X_test'] = X_test.to_numpy().tolist()
test_data['y_test'] = y_test.to_numpy().tolist()
with open('testdataDL.json', 'w') as tdfile:
    json.dump(test_data, tdfile)
    print('Test Data written to testdata.json')

Test Data written to testdata.json


In [ ]:
X_train=X_train.to_numpy()

In [ ]:
y_train=y_train.to_numpy()

In [ ]:
rfc=RandomForestClassifier(n_estimators=100)

In [ ]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
predictions=rfc.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
print(
    classification_report(y_test,predictions)
)

              precision    recall  f1-score   support

           0       0.70      0.83      0.76        64
           1       0.72      0.55      0.62        51

    accuracy                           0.70       115
   macro avg       0.71      0.69      0.69       115
weighted avg       0.71      0.70      0.70       115



In [ ]:
print(confusion_matrix(y_test.to_numpy(),predictions))
print(accuracy_score(y_test.to_numpy(),predictions))

[[899 258]
 [499 630]]
0.6688538932633421


In [ ]:
first_chunk=X[0:2000]
first_chunk_label=y[0:2000]

In [ ]:
first_chunk_pred=rfc.predict(first_chunk)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
print(classification_report(first_chunk_label,first_chunk_pred))

              precision    recall  f1-score   support

           0       0.65      0.77      0.71       997
           1       0.72      0.59      0.65      1003

    accuracy                           0.68      2000
   macro avg       0.69      0.68      0.68      2000
weighted avg       0.69      0.68      0.68      2000



In [ ]:
print(confusion_matrix(first_chunk_label.to_numpy(),first_chunk_pred))

[[772 225]
 [411 592]]


In [ ]:
second_chunk=X[2000:4000]
second_chunk_label=y[2000:4000]

In [ ]:
second_chunk_pred=rfc.predict(second_chunk)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
print(classification_report(second_chunk_label,second_chunk_pred))
print(confusion_matrix(second_chunk_label.to_numpy(),second_chunk_pred))

              precision    recall  f1-score   support

           0       0.63      0.78      0.70       999
           1       0.71      0.54      0.62      1001

    accuracy                           0.66      2000
   macro avg       0.67      0.66      0.66      2000
weighted avg       0.67      0.66      0.66      2000

[[777 222]
 [456 545]]


In [ ]:
third_chunk=X[4000:6000]
third_chunk_label=y[4000:6000]
third_chunk_pred=rfc.predict(third_chunk)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
print(classification_report(third_chunk_label,third_chunk_pred))
print(confusion_matrix(third_chunk_label.to_numpy(),third_chunk_pred))

              precision    recall  f1-score   support

           0       0.65      0.79      0.71      1011
           1       0.72      0.56      0.63       989

    accuracy                           0.68      2000
   macro avg       0.69      0.68      0.67      2000
weighted avg       0.69      0.68      0.67      2000

[[800 211]
 [436 553]]


In [ ]:
fourth_chunk=X[6000:8000]
fourth_chunk_label=y[6000:8000]
fourth_chunk_pred=rfc.predict(fourth_chunk)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
print(classification_report(fourth_chunk_label,fourth_chunk_pred))
print(confusion_matrix(fourth_chunk_label.to_numpy(),fourth_chunk_pred))

              precision    recall  f1-score   support

           0       0.64      0.78      0.70       980
           1       0.73      0.58      0.65      1020

    accuracy                           0.68      2000
   macro avg       0.69      0.68      0.68      2000
weighted avg       0.69      0.68      0.68      2000

[[762 218]
 [425 595]]


In [ ]:
fifth_chunk=X[8000:10000]
fifth_chunk_label=y[8000:10000]
fifth_chunk_pred=rfc.predict(fifth_chunk)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
print(classification_report(fifth_chunk_label,fifth_chunk_pred))
print(confusion_matrix(fifth_chunk_label.to_numpy(),fifth_chunk_pred))

              precision    recall  f1-score   support

           0       0.63      0.77      0.69      1003
           1       0.70      0.54      0.61       997

    accuracy                           0.65      2000
   macro avg       0.66      0.65      0.65      2000
weighted avg       0.66      0.65      0.65      2000

[[769 234]
 [457 540]]


In [ ]:
sixth_chunk=X[10000:]
sixth_chunk_label=y[10000:]
sixth_chunk_pred=rfc.predict(sixth_chunk)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
print(classification_report(sixth_chunk_label,sixth_chunk_pred))
print(confusion_matrix(sixth_chunk_label.to_numpy(),sixth_chunk_pred))

              precision    recall  f1-score   support

           0       0.65      0.80      0.72       725
           1       0.74      0.56      0.64       705

    accuracy                           0.68      1430
   macro avg       0.69      0.68      0.68      1430
weighted avg       0.69      0.68      0.68      1430

[[582 143]
 [308 397]]


In [ ]:
from sklearn.tree import _tree
def tree_to_json(tree):
    tree_ = tree.tree_
    feature_names = range(30)
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]
    def recurse(node):
        tree_json = dict()
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            tree_json['type'] = 'split'
            threshold = tree_.threshold[node]
            tree_json['threshold'] = "{} <= {}".format(feature_name[node], threshold)
            tree_json['left'] = recurse(tree_.children_left[node])
            tree_json['right'] = recurse(tree_.children_right[node])
        else:
            tree_json['type'] = 'leaf'
            tree_json['value'] = tree_.value[node].tolist()
        return tree_json

    return recurse(0)

def forest_to_json(forest):
    forest_json = dict()
    forest_json['n_features'] = forest.n_features_
    forest_json['n_classes'] = forest.n_classes_
    forest_json['classes'] = forest.classes_.tolist()
    forest_json['n_outputs'] = forest.n_outputs_
    forest_json['n_estimators'] = forest.n_estimators
    forest_json['estimators'] = [tree_to_json(estimator) for estimator in forest.estimators_]
    return forest_json

In [ ]:
json.dump(forest_to_json(rfc), open('classifierDL.json', 'w'))

In [ ]:
len(extracted[extracted['Deep_Learning']==0])

5637